In [1]:
import pandas as pd
import numpy as np 

teleco_df=pd.read_csv('Telco-Customer-Churn.csv')

teleco_df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [2]:
teleco_df.drop(['customerID'],axis = 1,inplace = True)

teleco_df

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85   
1                  No               Mailed check           56.95       1889.5   
2                 Yes               Mailed check           53.85       108.15   
3                  No  Bank transfer (automatic)           42.30      1840.75   
4                 Yes           Electronic check           70.70       151.65   
...               ...                        ...             ...          ...   
7038              Yes               Mailed check           84.80       1990.5   
7039              Yes    Credit card (automatic)          103.20       7362.9   
7040              Yes           Electronic check           29.60       346.45   
7041              Yes               Mailed check           74.40        306.6   
7042              Yes  Bank transfer (automatic)          105.65       6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 20 columns]

In [3]:
from sklearn import preprocessing 

obj_1 = list(teleco_df.select_dtypes(include=['object']).columns)
teleco_df[obj_1]

label_encoder = preprocessing.LabelEncoder() 

for column in obj_1:
    
    teleco_df[column] = label_encoder.fit_transform(teleco_df[column])

teleco_df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              0                0               2             2   
3              1                0               2             0   
4              0                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 0            0            0                0         0   
3                 2            2            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              2           29.85          2505      0  
1                 0              3           56.95          1466      0  
2                 1              3           53.85           157      1  
3                 0              0           42.30          1400      0  
4                 1              2           70.70           925      1

In [4]:
teleco_df['TotalCharges'] = teleco_df['TotalCharges'].fillna(0)

teleco_df

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0                 1                0               0             2   
1                 0                0               2             0   
2                 0                0               2             2   
3                 1                0               2             0   
4                 0                1               0             0   
...             ...              ...             ...           ...   
7038              2                0               2             0   
7039              2                1               0             2   
7040              1                0               2             0   
7041              2                1               0             0   
7042              0                1               2             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0   
1                    2            0            0                0         1   
2                    0            0            0                0         0   
3                    2            2            0                0         1   
4                    0            0            0                0         0   
...                ...          ...          ...              ...       ...   
7038                 2            2            2                2         1   
7039                 2            0            2                2         1   
7040                 0            0            0                0         0   
7041                 0            0            0                0         0   
7042                 2            2            2                2         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                    1              2           29.85          2505      0  
1                    0              3           56.95          1466      0  
2                    1              3           53.85           157      1  
3                    0              0           42.30          1400      0  
4                    1              2           70.70           925      1  
...                ...            ...             ...           ...    ...  
7038                 1              3           84.80          1597      0  
7039                 1              1          103.20          5698      0  
7040                 1              2           29.60          2994      0  
7041                 1              3           74.40          2660      1  
7042                 1              0          105.65          5407      0  

[7043 rows x 20 columns]

In [6]:
from sklearn.preprocessing import StandardScaler

teleco_df_1 = StandardScaler()
teleco_df_1.fit(teleco_df.drop(['Churn'],axis = 1))

attributes = teleco_df_1.transform(teleco_df.drop('Churn',axis = 1))

teleco_df_1

StandardScaler()

In [7]:
from sklearn.model_selection import train_test_split

X = attributes

Y = teleco_df['Churn']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state=27)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score ,classification_report, confusion_matrix

model1 = LogisticRegression()

model1.fit(X_train,Y_train)

y1_predicted = model1.predict(X_test)
y1_predicted

array([1, 0, 1, ..., 0, 1, 0])

In [9]:
print(classification_report(Y_test,y1_predicted))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1545
           1       0.67      0.52      0.59       568

    accuracy                           0.80      2113
   macro avg       0.75      0.71      0.73      2113
weighted avg       0.79      0.80      0.79      2113



In [10]:
accuracy_score(Y_test, y1_predicted)

0.8012304779933743

In [11]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier()

dt_classifier.fit(X_train, Y_train)

y2_predicted = dt_classifier.predict(X_test)

y2_predicted

array([1, 0, 1, ..., 0, 1, 0])

In [12]:
print(classification_report(Y_test,y2_predicted))


              precision    recall  f1-score   support

           0       0.82      0.80      0.81      1545
           1       0.48      0.51      0.50       568

    accuracy                           0.72      2113
   macro avg       0.65      0.66      0.65      2113
weighted avg       0.73      0.72      0.72      2113



In [13]:
accuracy_score(Y_test,y2_predicted)

0.7212494084240416

In [14]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, Y_train)

y3_predicted = svc.predict(X_test)

In [15]:
y3_predicted

array([1, 0, 1, ..., 0, 0, 0])

In [16]:
print(classification_report(Y_test,y3_predicted))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87      1545
           1       0.67      0.45      0.54       568

    accuracy                           0.79      2113
   macro avg       0.74      0.68      0.70      2113
weighted avg       0.78      0.79      0.78      2113



In [17]:
accuracy_score(Y_test,y3_predicted)

0.792238523426408

In [18]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_classifier = GaussianNB()

naive_bayes_classifier.fit(X_train, Y_train)

GaussianNB()

In [19]:
y4_predicted=naive_bayes_classifier.predict(X_test)

y4_predicted

array([1, 0, 1, ..., 0, 0, 0])

In [20]:
print(classification_report(Y_test,y4_predicted))

              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1545
           1       0.53      0.71      0.61       568

    accuracy                           0.75      2113
   macro avg       0.70      0.74      0.71      2113
weighted avg       0.79      0.75      0.76      2113



In [21]:
accuracy_score(Y_test,y4_predicted)

0.7529578797917653

In [22]:
from sklearn.neighbors import KNeighborsClassifier

custom_knnclassifier = KNeighborsClassifier(n_neighbors = 30)

custom_knnclassifier.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=30)

In [23]:
y5_predicted = custom_knnclassifier.predict(X_test)

In [24]:
print(accuracy_score(Y_test,y5_predicted))

0.7737813535257927
